{
 "title": "PostgreSQL Application Load",
 "tags": [
  "app",
  "postgres"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество подключений к БД",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"dvdrental\", instance=\"postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Запросы в секунду",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"dvdrental\"}[1m]) \r\n+ rate(pg_stat_database_xact_rollback{datname=\"dvdrental\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рекомендации с пометкой Critical",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_advisor_recommendations_total{severity=\"critical\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pg_stat_database_blks_hit{datname=\"dvdrental\"} \r\n / (pg_stat_database_blks_hit{datname=\"dvdrental\"} + pg_stat_database_blks_read{datname=\"dvdrental\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Рекомендаций активно",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_advisor_recommendations_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Медленные запросы",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(10, pg_stat_statements_mean_exec_time{datname=\"dvdrental\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Generation rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_wal_size_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}