groups:
- name: PostgreSQL
  rules:

  - alert: PostgresExporterDown
    expr: pg_up != 1
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL недоступен для exporter"

  - alert: HighConnectionCount
    expr: sum(pg_stat_activity_count{datname="dvdrental",backend_type="client backend"}) > 20
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Высокое число клиентских соединений к dvdrental"

  - alert: LowCacheHitRatio
    expr: (sum(rate(pg_stat_database_blks_hit{datname="dvdrental"}[5m])) / clamp_min(sum(rate(pg_stat_database_blks_hit{datname="dvdrental"}[5m])) + sum(rate(pg_stat_database_blks_read{datname="dvdrental"}[5m])), 1)) < 0.99
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "Cache hit ratio ниже 99% на dvdrental"

  - alert: SlowQueries
    expr: max((rate(pg_stat_statements_total_exec_time{datname="dvdrental"}[2m])) / clamp_min(rate(pg_stat_statements_calls{datname="dvdrental"}[2m]), 0.001)) > 1000
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Есть очень медленный запрос (>1000ms) за последние 2 минуты"

  - alert: SlowQueriesWarning
    expr: max((rate(pg_stat_statements_total_exec_time{datname="dvdrental"}[2m])) / clamp_min(rate(pg_stat_statements_calls{datname="dvdrental"}[2m]), 0.001)) > 250
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Есть заметно медленный запрос (>250ms) за последние 2 минуты"

  - alert: AdvisorCriticalRecommendations
    expr: sum(pg_advisor_recommendation_active{severity="critical"}) >= 3
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "pg-advisor обнаружил критические проблемы"

  - alert: AdvisorWarningRecommendations
    expr: sum(pg_advisor_recommendation_active{severity="warning"}) >= 6
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "pg-advisor обнаружил несколько предупреждений"